In [2]:
import numpy as np
import pandas as pd

In [28]:
print(np.arange(0,100, 20))
uniform = np.linspace(0, 20,6)
print(uniform)
np.eye(4) # matriz I
rand = np.random.rand(5,5)
print(rand)
rand_int = np.random.randint(1,15,(4,4))
print(rand_int)

[ 0 20 40 60 80]
[ 0.  4.  8. 12. 16. 20.]
[[0.2443628  0.85760118 0.5932726  0.96228321 0.19043383]
 [0.67867204 0.79911145 0.32723052 0.67937281 0.51523274]
 [0.78772832 0.94280442 0.79546132 0.7197629  0.51596786]
 [0.69296435 0.94916863 0.74528109 0.96326927 0.28103029]
 [0.82162678 0.25370272 0.58491524 0.57999127 0.72213473]]
[[ 4  4 14 10]
 [ 9  8 13  9]
 [10  4  4 12]
 [14  8 10 10]]


In [64]:
arr = np.random.randint(1,20,10)

matriz = arr.reshape(2,5)

#funciones principales
v = arr.max()
print(v)
v = matriz.max()
print(v)
v = matriz.max(0) # por columna
print(v)
v = matriz.max(1) # por fila
print(v)
v = arr.argmax() # menor indice en todo el array
print(v)
v = matriz.argmax(0) # mpor columna
print(v)
v = matriz.argmax(1) # por fila
print(v)
v = arr.min() # arr.argmin(0), arr.argmin(1), matriz.argmin(0), matriz.argmin(1), matriz.min()
print(v)
v = arr.ptp() #distancia entre el mayor y menor
print(v)
v = matriz.ptp(1)
print(v)
v = np.percentile(arr,50)#percentil
print(v)
arr.sort() # menor a mayor
v = np.median(arr) #mediana
print(arr)
v = np.std(arr) #desviacion estandar
print(v)
v = np.var(arr) #varianza
print(v)
v = np.mean(arr) #media
print(v)


19
19
[ 7 19 11 16 19]
[19 18]
1
[0 0 1 1 0]
[1 4]
4
15
[15 14]
11.5
[ 4  4  7  8 11 12 16 18 19 19]
5.653317610041028
31.959999999999997
11.8


In [176]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [100]:
#concatenar
a = np.array([[1,2],[3,4]])
b = np.array([5,6])


In [79]:
print(a.ndim)
print(b.ndim)

2
1


In [85]:
b = np.expand_dims(b, axis = 0)
np.concatenate((a,b), axis = 0)



array([[1, 2],
       [3, 4],
       [5, 6]])

In [101]:
b = np.expand_dims(b, axis = 0)
print(a)
print(b.T)
np.concatenate((a,b.T), axis = 1) #transpuesta np.transpose(arr)


[[1 2]
 [3 4]]
[[5]
 [6]]


array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
#USAR SIEMPRE EL COPY CUANDO SACAMOS TROZOS DE UN ARRAY
arr.copy()

In [102]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [104]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [105]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [106]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [107]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [110]:
matriz

array([[ 4,  4,  7,  8, 11],
       [12, 16, 18, 19, 19]])

In [128]:
matriz[matriz[:,] > 5]

array([ 7,  8, 11, 12, 16, 18, 19, 19])

In [131]:
#OPERACIONES
arr = np.arange(0,10)
arr2 = arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
arr * 2 #solo en numpy

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [132]:
1/arr

/tmp/ipykernel_13493/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [133]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [134]:
arr + arr2 #indice por indice inclusive para matrices

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [135]:
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [136]:
matriz2 = matriz.copy()

In [137]:
np.matmul(matriz, matriz2.T) #producto puntop

array([[ 30,  80],
       [ 80, 255]])

In [138]:
matriz @ matriz2.T #producto punto

array([[ 30,  80],
       [ 80, 255]])

## PANDAS

### pandas series
indices y datos, igual a un np array
### pandas dataframes
objeto de arrays en una estructura matricial, las filas y las columnas tienen indices(se basa en series)

In [139]:
import pandas as pd

In [141]:
psg_players = pd.Series(['Navas', 'Mbappe', 'Neymar', 'Messi'],
 index = [ 1, 7, 10, 30])

In [142]:
psg_players

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [143]:
dict = {1:'Navas', 7:'Mbappe', 10:'Neymar', 30:'Messi'}
pd.Series(dict)

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [144]:
psg_players

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [147]:
psg_players[0:2]

1     Navas
7    Mbappe
dtype: object

In [148]:
dict = {'Jugador':['Navas', 'Mbappe', 'Neymar', 'Messi'],
 'Altura': [183.0,170.0,170.0, 165.0],
 'Goles': [2,200,200,200]
 }


In [152]:
df_players = pd.DataFrame(dict)

In [154]:
df_players.columns

Index(['Jugador', 'Altura', 'Goles'], dtype='object')

In [155]:
df_players.index

RangeIndex(start=0, stop=4, step=1)

In [234]:
df_mr = pd.read_csv("Movie_Ratings.csv")


In [ ]:
df_mr['Bryan'] #columns
df_mr[0:4] #index
#no se puede hacer por ambos el filtrado para eso se usa
#loc


In [180]:
#va del indice 0 hasta el 4 no como arange
df_mr.loc[0:4, ['Heather','Bryan'] ] 


Heather  Bryan
0      NaN    2.0
1      5.0    5.0
2      NaN    NaN
3      NaN    5.0
4      4.0    3.0

In [181]:
#loc acepta operadores y solo afecta a los valores
df_mr.loc[0:4, ['Heather', 'Bryan']] * -1

Heather  Bryan
0      NaN   -2.0
1     -5.0   -5.0
2      NaN    NaN
3      NaN   -5.0
4     -4.0   -3.0

In [197]:
#iloc permite slicing con indices
df_mr.iloc[0:4, 0:3]

Unnamed: 0  Patrick C  Heather
0         Alien        NaN      NaN
1        Avatar        4.0      5.0
2  Blade Runner        5.0      NaN
3    Braveheart        4.0      NaN

In [207]:
#agregar o eliminar datos
df_mr.head(2)

Unnamed: 0  Patrick C  Heather  Patrick T  Thomas  aaron  vanessa  greg  \
0      Alien        NaN      NaN        NaN     5.0    4.0      NaN   NaN   
1     Avatar        4.0      5.0        4.0     2.0    NaN      4.0   3.0   

   brian  ben  ...  Zak  Matt  Chris.1  Josh  Amy  Valerie  Gary  Stephen  \
0    4.0  NaN  ...  NaN   NaN      4.0   3.0  NaN      NaN   2.0      5.0   
1    NaN  3.0  ...  5.0   NaN      NaN   4.0  3.0      2.0   1.0      4.0   

   Jessica  Jeff  
0      NaN   4.0  
1      NaN   4.0  

[2 rows x 25 columns]

In [206]:
#drop columns, solo borra la salida,
#usar inplace=True para borrar de forma permanetne
df_mr.drop('Bryan', axis=1).head(2)

KeyError: "['Bryan'] not found in axis"

In [205]:
df_mr.head(2)

Unnamed: 0  Patrick C  Heather  Patrick T  Thomas  aaron  vanessa  greg  \
0      Alien        NaN      NaN        NaN     5.0    4.0      NaN   NaN   
1     Avatar        4.0      5.0        4.0     2.0    NaN      4.0   3.0   

   brian  ben  ...  Zak  Matt  Chris.1  Josh  Amy  Valerie  Gary  Stephen  \
0    4.0  NaN  ...  NaN   NaN      4.0   3.0  NaN      NaN   2.0      5.0   
1    NaN  3.0  ...  5.0   NaN      NaN   4.0  3.0      2.0   1.0      4.0   

   Jessica  Jeff  
0      NaN   4.0  
1      NaN   4.0  

[2 rows x 25 columns]

In [208]:
df_mr.drop(0, axis=0).head(2)

Unnamed: 0  Patrick C  Heather  Patrick T  Thomas  aaron  vanessa  greg  \
1        Avatar        4.0      5.0        4.0     2.0    NaN      4.0   3.0   
2  Blade Runner        5.0      NaN        NaN     5.0    4.0      NaN   1.0   

   brian  ben  ...  Zak  Matt  Chris.1  Josh  Amy  Valerie  Gary  Stephen  \
1    NaN  3.0  ...  5.0   NaN      NaN   4.0  3.0      2.0   1.0      4.0   
2    5.0  5.0  ...  NaN   NaN      3.0   NaN  3.0      3.0   1.0      NaN   

   Jessica  Jeff  
1      NaN   4.0  
2      NaN   5.0  

[2 rows x 25 columns]

In [209]:
#Add columns
df_mr.head(2)

Unnamed: 0  Patrick C  Heather  Patrick T  Thomas  aaron  vanessa  greg  \
0      Alien        NaN      NaN        NaN     5.0    4.0      NaN   NaN   
1     Avatar        4.0      5.0        4.0     2.0    NaN      4.0   3.0   

   brian  ben  ...  Zak  Matt  Chris.1  Josh  Amy  Valerie  Gary  Stephen  \
0    4.0  NaN  ...  NaN   NaN      4.0   3.0  NaN      NaN   2.0      5.0   
1    NaN  3.0  ...  5.0   NaN      NaN   4.0  3.0      2.0   1.0      4.0   

   Jessica  Jeff  
0      NaN   4.0  
1      NaN   4.0  

[2 rows x 25 columns]

In [211]:
df_mr['nueva_c'] = np.nan
df_mr.head(2)

Unnamed: 0  Patrick C  Heather  Patrick T  Thomas  aaron  vanessa  greg  \
0      Alien        NaN      NaN        NaN     5.0    4.0      NaN   NaN   
1     Avatar        4.0      5.0        4.0     2.0    NaN      4.0   3.0   

   brian  ben  ...  Matt  Chris.1  Josh  Amy  Valerie  Gary  Stephen  Jessica  \
0    4.0  NaN  ...   NaN      4.0   3.0  NaN      NaN   2.0      5.0      NaN   
1    NaN  3.0  ...   NaN      NaN   4.0  3.0      2.0   1.0      4.0      NaN   

   Jeff  nueva_c  
0   4.0      NaN  
1   4.0      NaN  

[2 rows x 26 columns]

In [213]:
data = np.arange(0, df_mr.shape[0])
df_mr['Test2'] = data
df_mr.tail()

Unnamed: 0  Patrick C  Heather  Patrick T  Thomas  aaron  vanessa  \
20  The Happening        1.0      NaN        NaN     1.0    NaN      NaN   
21     The Matrix        3.0      4.0        5.0     4.0    4.0      4.0   
22      Toy Story        4.0      3.0        4.0     4.0    5.0      4.0   
23        Village        NaN      2.0        1.0     1.0    NaN      2.0   
24   You Got Mail        1.0      NaN        1.0     1.0    3.0      NaN   

    greg  brian  ben  ...  Chris.1  Josh  Amy  Valerie  Gary  Stephen  \
20   NaN    2.0  NaN  ...      NaN   NaN  NaN      1.0   NaN      1.0   
21   4.0    5.0  4.0  ...      2.0   5.0  5.0      4.0   2.0      5.0   
22   5.0    5.0  5.0  ...      4.0   4.0  4.0      5.0   4.0      4.0   
23   NaN    4.0  3.0  ...      1.0   4.0  NaN      2.0   NaN      2.0   
24   NaN    3.0  NaN  ...      1.0   NaN  2.0      2.0   1.0      2.0   

    Jessica  Jeff  nueva_c  Test2  
20      NaN   NaN      NaN     20  
21      NaN   5.0      NaN     21  
22      5.0   5.0      NaN     22  
23      NaN   2.0      NaN     23  
24      NaN   2.0      NaN     24  

[5 rows x 27 columns]

In [217]:
##AGREGAR FILAS RAPIDO Y RECOMENDADO
df_mr.tail(2)

Unnamed: 0  Patrick C  Heather  Patrick T  Thomas  aaron  vanessa  greg  \
23       Village        NaN      2.0        1.0     1.0    NaN      2.0   NaN   
24  You Got Mail        1.0      NaN        1.0     1.0    3.0      NaN   NaN   

    brian  ben  ...  Chris.1  Josh  Amy  Valerie  Gary  Stephen  Jessica  \
23    4.0  3.0  ...      1.0   4.0  NaN      2.0   NaN      2.0      NaN   
24    3.0  NaN  ...      1.0   NaN  2.0      2.0   1.0      2.0      NaN   

    Jeff  nueva_c  Test2  
23   2.0      NaN     23  
24   2.0      NaN     24  

[2 rows x 27 columns]

In [219]:
df_mr.append(df_mr)
df_mr.tail()

/tmp/ipykernel_13493/916962394.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_mr.append(df_mr)


Unnamed: 0  Patrick C  Heather  Patrick T  Thomas  aaron  vanessa  \
20  The Happening        1.0      NaN        NaN     1.0    NaN      NaN   
21     The Matrix        3.0      4.0        5.0     4.0    4.0      4.0   
22      Toy Story        4.0      3.0        4.0     4.0    5.0      4.0   
23        Village        NaN      2.0        1.0     1.0    NaN      2.0   
24   You Got Mail        1.0      NaN        1.0     1.0    3.0      NaN   

    greg  brian  ben  ...  Chris.1  Josh  Amy  Valerie  Gary  Stephen  \
20   NaN    2.0  NaN  ...      NaN   NaN  NaN      1.0   NaN      1.0   
21   4.0    5.0  4.0  ...      2.0   5.0  5.0      4.0   2.0      5.0   
22   5.0    5.0  5.0  ...      4.0   4.0  4.0      5.0   4.0      4.0   
23   NaN    4.0  3.0  ...      1.0   4.0  NaN      2.0   NaN      2.0   
24   NaN    3.0  NaN  ...      1.0   NaN  2.0      2.0   1.0      2.0   

    Jessica  Jeff  nueva_c  Test2  
20      NaN   NaN      NaN     20  
21      NaN   5.0      NaN     21  
22      5.0   5.0      NaN     22  
23      NaN   2.0      NaN     23  
24      NaN   2.0      NaN     24  

[5 rows x 27 columns]

In [221]:
 df_mr.isnull()

Unnamed: 0  Patrick C  Heather  Patrick T  Thomas  aaron  vanessa   greg  \
0        False       True     True       True   False  False     True   True   
1        False      False    False      False   False   True    False  False   
2        False      False     True       True   False  False     True  False   
3        False      False     True       True   False  False    False  False   
4        False      False    False      False   False   True    False  False   
5        False      False    False      False   False   True    False  False   
6        False       True    False       True   False  False    False  False   
7        False       True    False       True   False   True    False  False   
8        False      False     True      False   False   True     True   True   
9        False      False    False      False    True  False    False  False   
10       False      False    False      False   False  False    False  False   
11       False      False     True      False   False   True    False  False   
12       False       True     True      False    True   True    False   True   
13       False       True     True       True   False  False     True  False   
14       False       True    False       True   False  False    False  False   
15       False      False     True       True    True  False     True  False   
16       False      False    False       True   False   True     True   True   
17       False      False    False      False   False  False     True  False   
18       False      False    False      False   False  False    False  False   
19       False      False    False      False   False   True     True  False   
20       False      False     True       True   False   True     True   True   
21       False      False    False      False   False  False    False  False   
22       False      False    False      False   False  False    False  False   
23       False       True    False      False   False   True    False   True   
24       False      False     True      False   False  False     True   True   

    brian    ben  ...  Chris.1   Josh    Amy  Valerie   Gary  Stephen  \
0   False   True  ...    False  False   True     True  False    False   
1    True  False  ...     True  False  False    False  False    False   
2   False  False  ...    False   True  False    False  False     True   
3   False   True  ...    False   True  False    False  False    False   
4   False  False  ...    False   True  False    False  False    False   
5   False  False  ...    False  False  False    False  False    False   
6   False  False  ...    False  False   True    False  False    False   
7   False  False  ...    False  False  False    False  False    False   
8   False   True  ...     True   True  False    False  False     True   
9   False  False  ...    False   True   True    False  False    False   
10  False  False  ...    False   True  False    False  False    False   
11  False  False  ...    False   True  False    False  False     True   
12  False  False  ...    False   True   True     True   True     True   
13  False  False  ...    False   True  False    False  False    False   
14   True  False  ...    False   True   True    False  False     True   
15  False  False  ...    False   True  False    False  False     True   
16  False  False  ...    False   True  False    False  False     True   
17  False  False  ...    False  False  False    False  False    False   
18  False  False  ...    False  False   True    False  False    False   
19  False  False  ...    False  False  False    False   True    False   
20  False   True  ...     True   True   True    False   True    False   
21  False  False  ...    False  False  False    False  False    False   
22  False  False  ...    False  False  False    False  False    False   
23  False  False  ...    False  False   True    False   True    False   
24  False   True  ...    False   True  False    False  False    False   

    Jessica   Jeff  nuev

In [222]:
df_mr.isnull()*1

Unnamed: 0  Patrick C  Heather  Patrick T  Thomas  aaron  vanessa  greg  \
0            0          1        1          1       0      0        1     1   
1            0          0        0          0       0      1        0     0   
2            0          0        1          1       0      0        1     0   
3            0          0        1          1       0      0        0     0   
4            0          0        0          0       0      1        0     0   
5            0          0        0          0       0      1        0     0   
6            0          1        0          1       0      0        0     0   
7            0          1        0          1       0      1        0     0   
8            0          0        1          0       0      1        1     1   
9            0          0        0          0       1      0        0     0   
10           0          0        0          0       0      0        0     0   
11           0          0        1          0       0      1        0     0   
12           0          1        1          0       1      1        0     1   
13           0          1        1          1       0      0        1     0   
14           0          1        0          1       0      0        0     0   
15           0          0        1          1       1      0        1     0   
16           0          0        0          1       0      1        1     1   
17           0          0        0          0       0      0        1     0   
18           0          0        0          0       0      0        0     0   
19           0          0        0          0       0      1        1     0   
20           0          0        1          1       0      1        1     1   
21           0          0        0          0       0      0        0     0   
22           0          0        0          0       0      0        0     0   
23           0          1        0          0       0      1        0     1   
24           0          0        1          0       0      0        1     1   

    brian  ben  ...  Chris.1  Josh  Amy  Valerie  Gary  Stephen  Jessica  \
0       0    1  ...        0     0    1        1     0        0        1   
1       1    0  ...        1     0    0        0     0        0        1   
2       0    0  ...        0     1    0        0     0        1        1   
3       0    1  ...        0     1    0        0     0        0        1   
4       0    0  ...        0     1    0        0     0        0        1   
5       0    0  ...        0     0    0        0     0        0        0   
6       0    0  ...        0     0    1        0     0        0        1   
7       0    0  ...        0     0    0        0     0        0        0   
8       0    1  ...        1     1    0        0     0        1        0   
9       0    0  ...        0     1    1        0     0        0        0   
10      0    0  ...        0     1    0        0     0        0        0   
11      0    0  ...        0     1    0        0     0        1        0   
12      0    0  ...        0     1    1        1     1        1        1   
13      0    0  ...        0     1    0        0     0        0        0   
14      1    0  ...        0     1    1        0     0        1        1   
15      0    0  ...        0     1    0        0     0        1        1   
16      0    0  ...        0     1    0        0     0        1        0   
17      0    0  ...        0     0    0        0     0        0        0   
18      0    0  ...        0     0    1        0     0        0        0   
19      0    0  ...        0     0    0        0     1        0        0   
20      0    1  ...        1     1    1        0     1        0        1   
21      0    0  ...        0     0    0        0     0        0        1   
22      0    0  ...        0     0    0        0     0        0        0   
23      0    0  ...        0     0    1        0     1        0        1   
24      0    1  ...        0     1    0        0 

In [224]:
df_mr.head(2).fillna('Missing')

Unnamed: 0 Patrick C  Heather Patrick T  Thomas    aaron  vanessa     greg  \
0      Alien   Missing  Missing   Missing     5.0      4.0  Missing  Missing   
1     Avatar       4.0      5.0       4.0     2.0  Missing      4.0      3.0   

     brian      ben  ...  Chris.1 Josh      Amy  Valerie  Gary Stephen  \
0      4.0  Missing  ...      4.0  3.0  Missing  Missing   2.0     5.0   
1  Missing      3.0  ...  Missing  4.0      3.0      2.0   1.0     4.0   

   Jessica Jeff  nueva_c Test2  
0  Missing  4.0  Missing     0  
1  Missing  4.0  Missing     1  

[2 rows x 27 columns]

In [227]:
df = df_mr.iloc[0:10, 0:5]
df

Unnamed: 0  Patrick C  Heather  Patrick T  Thomas
0              Alien        NaN      NaN        NaN     5.0
1             Avatar        4.0      5.0        4.0     2.0
2       Blade Runner        5.0      NaN        NaN     5.0
3         Braveheart        4.0      NaN        NaN     4.0
4          Dodgeball        5.0      4.0        2.0     4.0
5        Forest Gump        4.0      5.0        3.0     3.0
6          Gladiator        NaN      5.0        NaN     4.0
7               Jaws        NaN      5.0        NaN     4.0
8             Kazaam        2.0      NaN        5.0     2.0
9  Lord of the Rings        4.0      4.0        2.0     NaN

In [228]:
df.fillna(df.mean()) #llena con la media

/tmp/ipykernel_13493/634187881.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean())


Unnamed: 0  Patrick C   Heather  Patrick T    Thomas
0              Alien        4.0  4.666667        3.2  5.000000
1             Avatar        4.0  5.000000        4.0  2.000000
2       Blade Runner        5.0  4.666667        3.2  5.000000
3         Braveheart        4.0  4.666667        3.2  4.000000
4          Dodgeball        5.0  4.000000        2.0  4.000000
5        Forest Gump        4.0  5.000000        3.0  3.000000
6          Gladiator        4.0  5.000000        3.2  4.000000
7               Jaws        4.0  5.000000        3.2  4.000000
8             Kazaam        2.0  4.666667        5.0  2.000000
9  Lord of the Rings        4.0  4.000000        2.0  3.666667

In [229]:
df.interpolate() #llena los nulos con una serie

Unnamed: 0  Patrick C   Heather  Patrick T  Thomas
0              Alien        NaN       NaN        NaN     5.0
1             Avatar   4.000000  5.000000   4.000000     2.0
2       Blade Runner   5.000000  4.666667   3.333333     5.0
3         Braveheart   4.000000  4.333333   2.666667     4.0
4          Dodgeball   5.000000  4.000000   2.000000     4.0
5        Forest Gump   4.000000  5.000000   3.000000     3.0
6          Gladiator   3.333333  5.000000   3.666667     4.0
7               Jaws   2.666667  5.000000   4.333333     4.0
8             Kazaam   2.000000  4.500000   5.000000     2.0
9  Lord of the Rings   4.000000  4.000000   2.000000     2.0

In [233]:
df.dropna() #borrar los datos nulos algunos cinetifios lo usan
df_test = df.dropna()


Unnamed: 0
1     Avatar

In [239]:
df = df_mr.copy()

In [237]:
#condicionales igual que numpy
# ~ este simbolo es negacion y se puede usar en
# estas condicionales
df[df['Thomas'] > 4]

Unnamed: 0  Patrick C  Heather  Bryan  Patrick T  Thomas  aaron  \
0               Alien        NaN      NaN    2.0        NaN     5.0    4.0   
2        Blade Runner        5.0      NaN    NaN        NaN     5.0    4.0   
10  Napolean Dynamite        3.0      4.0    1.0        1.0     5.0    1.0   
11         Old School        3.0      NaN    4.0        5.0     5.0    NaN   
14           Scarface        NaN      4.0    NaN        NaN     5.0    4.0   
17          Spiderman        4.0      3.0    4.0        4.0     5.0    3.0   
18          Star Wars        5.0      5.0    4.0        5.0     5.0    3.0   

    vanessa  greg  brian  ...  Zak  Matt  Chris.1  Josh  Amy  Valerie  Gary  \
0       NaN   NaN    4.0  ...  NaN   NaN      4.0   3.0  NaN      NaN   2.0   
2       NaN   1.0    5.0  ...  NaN   NaN      3.0   NaN  3.0      3.0   1.0   
10      4.0   4.0    4.0  ...  1.0   3.0      1.0   NaN  2.0      5.0   4.0   
11      3.0   5.0    4.0  ...  5.0   NaN      4.0   NaN  3.0      3.0   5.0   
14      4.0   4.0    NaN  ...  3.0   NaN      2.0   NaN  NaN      4.0   3.0   
17      NaN   4.0    4.0  ...  3.0   3.0      2.0   4.0  3.0      5.0   2.0   
18      3.0   5.0    5.0  ...  5.0   NaN      5.0   5.0  NaN      5.0   5.0   

    Stephen  Jessica  Jeff  
0       5.0      NaN   4.0  
2       NaN      NaN   5.0  
10      2.0      2.0   3.0  
11      NaN      2.0   3.0  
14      NaN      NaN   NaN  
17      3.0      3.0   4.0  
18      5.0      5.0   5.0  

[7 rows x 26 columns]

In [240]:
df.describe() #importante

Patrick C    Heather      Bryan  Patrick T     Thomas      aaron  \
count  18.000000  15.000000  22.000000  15.000000  22.000000  14.000000   
mean    3.611111   3.933333   3.363636   3.133333   3.681818   3.714286   
std     1.243283   1.222799   1.328997   1.641718   1.393398   1.069045   
min     1.000000   1.000000   1.000000   1.000000   1.000000   1.000000   
25%     3.000000   3.500000   3.000000   1.500000   3.250000   3.000000   
50%     4.000000   4.000000   3.500000   4.000000   4.000000   4.000000   
75%     4.000000   5.000000   4.000000   4.500000   5.000000   4.000000   
max     5.000000   5.000000   5.000000   5.000000   5.000000   5.000000   

         vanessa       greg      brian        ben  ...        Zak      Matt  \
count  15.000000  18.000000  23.000000  20.000000  ...  19.000000  6.000000   
mean    3.200000   4.055556   3.869565   3.750000  ...   3.736842  2.666667   
std     1.014185   1.055642   1.254242   1.332785  ...   1.521772  1.366260   
min     1.000000   1.000000   1.000000   1.000000  ...   1.000000  1.000000   
25%     2.500000   4.000000   3.000000   3.000000  ...   3.000000  1.500000   
50%     4.000000   4.000000   4.000000   4.000000  ...   4.000000  3.000000   
75%     4.000000   5.000000   5.000000   5.000000  ...   5.000000  3.750000   
max     4.000000   5.000000   5.000000   5.000000  ...   5.000000  4.000000   

         Chris.1       Josh        Amy    Valerie       Gary    Stephen  \
count  22.000000  11.000000  17.000000  23.000000  21.000000  18.000000   
mean    3.181818   4.181818   3.058824   3.391304   3.047619   3.333333   
std     1.401916   0.603023   1.028992   1.469048   1.430950   1.414214   
min     1.000000   3.000000   1.000000   1.000000   1.000000   1.000000   
25%     2.000000   4.000000   2.000000   2.000000   2.000000   2.000000   
50%     3.500000   4.000000   3.000000   3.000000   3.000000   3.500000   
75%     4.000000   4.500000   4.000000   5.000000   4.000000   4.750000   
max     5.000000   5.000000   5.000000   5.000000   5.000000   5.000000   

         Jessica       Jeff  
count  12.000000  22.000000  
mean    3.250000   3.636364  
std     1.356801   1.292670  
min     1.000000   1.000000  
25%     2.000000   3.000000  
50%     3.000000   4.000000  
75%     4.250000   5.000000  
max     5.000000   5.000000  

[8 rows x 25 columns]

In [241]:
df.memory_usage(deep=True)

Index          128
Unnamed: 0    1693
Patrick C      200
Heather        200
Bryan          200
Patrick T      200
Thomas         200
aaron          200
vanessa        200
greg           200
brian          200
ben            200
Katherine      200
Jonathan       200
Zwe            200
Erin           200
Chris          200
Zak            200
Matt           200
Chris.1        200
Josh           200
Amy            200
Valerie        200
Gary           200
Stephen        200
Jessica        200
Jeff           200
dtype: int64

In [242]:
df['Jeff'].value_counts()

5.0    7
4.0    6
3.0    5
1.0    2
2.0    2
Name: Jeff, dtype: int64

In [ ]:
df.drop_duplicates()#elimina filas completamente iguales
df.sort_values('Jeff') #order por columna

In [246]:
#GROUP BY
df.groupby('Jeff').sum() #simples
#llaves compuestas
#

Patrick C  Heather  Bryan  Patrick T  Thomas  aaron  vanessa  greg  \
Jeff                                                                       
1.0         6.0      1.0    5.0        5.0     6.0    0.0      0.0   0.0   
2.0         1.0      2.0    4.0        2.0     2.0    3.0      2.0   0.0   
3.0        15.0     12.0   15.0       10.0    18.0    9.0     13.0  21.0   
4.0        16.0     18.0   25.0       11.0    23.0   15.0     15.0  21.0   
5.0        21.0     22.0   20.0       19.0    26.0   16.0     14.0  22.0   

      brian   ben  ...  Chris   Zak  Matt  Chris.1  Josh   Amy  Valerie  Gary  \
Jeff               ...                                                          
1.0     4.0   2.0  ...    4.0   1.0   1.0      3.0   0.0   3.0      2.0   3.0   
2.0     7.0   3.0  ...    3.0   6.0   0.0      2.0   4.0   2.0      4.0   1.0   
3.0    21.0  18.0  ...   17.0  18.0   4.0     17.0   0.0  13.0     19.0  19.0   
4.0    22.0  17.0  ...   13.0  23.0   7.0     18.0  19.0  13.0     19.0  17.0   
5.0    28.0  26.0  ...   24.0  19.0   4.0     24.0  23.0  19.0     24.0  16.0   

      Stephen  Jessica  
Jeff                    
1.0       0.0      3.0  
2.0       4.0      0.0  
3.0      13.0     11.0  
4.0      22.0      7.0  
5.0      20.0     18.0  

[5 rows x 24 columns]

In [249]:
#diferentes filtros 
df.groupby('{Jeff').agg({'Bryan':['min','max'], 'Jeff' :['sum']})

Bryan       Jeff
       min  max   sum
Jeff                 
1.0    2.0  3.0   2.0
2.0    1.0  3.0   4.0
3.0    1.0  4.0  15.0
4.0    2.0  5.0  24.0
5.0    1.0  5.0  35.0

In [ ]:
#merge, join, concat
pd.concat([df1,df2], axis = 1)#dependiente de indice
#merge
