In [2]:
import numpy as np
import pandas as pd

In [28]:
print(np.arange(0,100, 20))
uniform = np.linspace(0, 20,6)
print(uniform)
np.eye(4) # matriz I
rand = np.random.rand(5,5)
print(rand)
rand_int = np.random.randint(1,15,(4,4))
print(rand_int)

[ 0 20 40 60 80]
[ 0.  4.  8. 12. 16. 20.]
[[0.2443628  0.85760118 0.5932726  0.96228321 0.19043383]
 [0.67867204 0.79911145 0.32723052 0.67937281 0.51523274]
 [0.78772832 0.94280442 0.79546132 0.7197629  0.51596786]
 [0.69296435 0.94916863 0.74528109 0.96326927 0.28103029]
 [0.82162678 0.25370272 0.58491524 0.57999127 0.72213473]]
[[ 4  4 14 10]
 [ 9  8 13  9]
 [10  4  4 12]
 [14  8 10 10]]


In [64]:
arr = np.random.randint(1,20,10)

matriz = arr.reshape(2,5)

#funciones principales
v = arr.max()
print(v)
v = matriz.max()
print(v)
v = matriz.max(0) # por columna
print(v)
v = matriz.max(1) # por fila
print(v)
v = arr.argmax() # menor indice en todo el array
print(v)
v = matriz.argmax(0) # mpor columna
print(v)
v = matriz.argmax(1) # por fila
print(v)
v = arr.min() # arr.argmin(0), arr.argmin(1), matriz.argmin(0), matriz.argmin(1), matriz.min()
print(v)
v = arr.ptp() #distancia entre el mayor y menor
print(v)
v = matriz.ptp(1)
print(v)
v = np.percentile(arr,50)#percentil
print(v)
arr.sort() # menor a mayor
v = np.median(arr) #mediana
print(arr)
v = np.std(arr) #desviacion estandar
print(v)
v = np.var(arr) #varianza
print(v)
v = np.mean(arr) #media
print(v)


19
19
[ 7 19 11 16 19]
[19 18]
1
[0 0 1 1 0]
[1 4]
4
15
[15 14]
11.5
[ 4  4  7  8 11 12 16 18 19 19]
5.653317610041028
31.959999999999997
11.8


In [176]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [100]:
#concatenar
a = np.array([[1,2],[3,4]])
b = np.array([5,6])


In [79]:
print(a.ndim)
print(b.ndim)

2
1


In [85]:
b = np.expand_dims(b, axis = 0)
np.concatenate((a,b), axis = 0)



array([[1, 2],
       [3, 4],
       [5, 6]])

In [101]:
b = np.expand_dims(b, axis = 0)
print(a)
print(b.T)
np.concatenate((a,b.T), axis = 1) #transpuesta np.transpose(arr)


[[1 2]
 [3 4]]
[[5]
 [6]]


array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
#USAR SIEMPRE EL COPY CUANDO SACAMOS TROZOS DE UN ARRAY
arr.copy()

In [102]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [104]:
indices_cond = arr > 5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [105]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [106]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [107]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [110]:
matriz

array([[ 4,  4,  7,  8, 11],
       [12, 16, 18, 19, 19]])

In [128]:
matriz[matriz[:,] > 5]

array([ 7,  8, 11, 12, 16, 18, 19, 19])

In [131]:
#OPERACIONES
arr = np.arange(0,10)
arr2 = arr.copy()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [130]:
arr * 2 #solo en numpy

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [132]:
1/arr

/tmp/ipykernel_13493/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [133]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [134]:
arr + arr2 #indice por indice inclusive para matrices

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [135]:
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [136]:
matriz2 = matriz.copy()

In [137]:
np.matmul(matriz, matriz2.T) #producto puntop

array([[ 30,  80],
       [ 80, 255]])

In [138]:
matriz @ matriz2.T #producto punto

array([[ 30,  80],
       [ 80, 255]])

## PANDAS

### pandas series
indices y datos, igual a un np array
### pandas dataframes
objeto de arrays en una estructura matricial, las filas y las columnas tienen indices(se basa en series)

In [139]:
import pandas as pd

In [141]:
psg_players = pd.Series(['Navas', 'Mbappe', 'Neymar', 'Messi'],
 index = [ 1, 7, 10, 30])

In [142]:
psg_players

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [143]:
dict = {1:'Navas', 7:'Mbappe', 10:'Neymar', 30:'Messi'}
pd.Series(dict)

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [144]:
psg_players

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [147]:
psg_players[0:2]

1     Navas
7    Mbappe
dtype: object

In [148]:
dict = {'Jugador':['Navas', 'Mbappe', 'Neymar', 'Messi'],
 'Altura': [183.0,170.0,170.0, 165.0],
 'Goles': [2,200,200,200]
 }


In [152]:
df_players = pd.DataFrame(dict)

In [154]:
df_players.columns

Index(['Jugador', 'Altura', 'Goles'], dtype='object')

In [155]:
df_players.index

RangeIndex(start=0, stop=4, step=1)

In [165]:
df_mr = pd.read_csv("Movie_Ratings.csv")


Unnamed: 0  Patrick C  Heather  Bryan  Patrick T  Thomas  aaron  vanessa  \
0         Alien        NaN      NaN    2.0        NaN     5.0    4.0      NaN   
1        Avatar        4.0      5.0    5.0        4.0     2.0    NaN      4.0   
2  Blade Runner        5.0      NaN    NaN        NaN     5.0    4.0      NaN   
3    Braveheart        4.0      NaN    5.0        NaN     4.0    4.0      3.0   
4     Dodgeball        5.0      4.0    3.0        2.0     4.0    NaN      4.0   

   greg  brian  ...  Zak  Matt  Chris.1  Josh  Amy  Valerie  Gary  Stephen  \
0   NaN    4.0  ...  NaN   NaN      4.0   3.0  NaN      NaN   2.0      5.0   
1   3.0    NaN  ...  5.0   NaN      NaN   4.0  3.0      2.0   1.0      4.0   
2   1.0    5.0  ...  NaN   NaN      3.0   NaN  3.0      3.0   1.0      NaN   
3   4.0    4.0  ...  5.0   NaN      4.0   NaN  3.0      4.0   5.0      5.0   
4   5.0    3.0  ...  3.0   NaN      3.0   NaN  4.0      3.0   4.0      3.0   

   Jessica  Jeff  
0      NaN   4.0  
1      NaN   4.0  
2      NaN   5.0  
3      NaN   4.0  
4      NaN   3.0  

[5 rows x 26 columns]

In [ ]:
df_mr['Bryan'] #columns
df_mr[0:4] #index
#no se puede hacer por ambos el filtrado para eso se usa
#loc


In [180]:
#va del indice 0 hasta el 4 no como arange
df_mr.loc[0:4, ['Heather','Bryan'] ] 


Heather  Bryan
0      NaN    2.0
1      5.0    5.0
2      NaN    NaN
3      NaN    5.0
4      4.0    3.0

In [181]:
#loc acepta operadores y solo afecta a los valores
df_mr.loc[0:4, ['Heather', 'Bryan']] * -1

Heather  Bryan
0      NaN   -2.0
1     -5.0   -5.0
2      NaN    NaN
3      NaN   -5.0
4     -4.0   -3.0

In [197]:
#iloc permite slicing con indices
df_mr.iloc[0:4, 0:3]

Unnamed: 0  Patrick C  Heather
0         Alien        NaN      NaN
1        Avatar        4.0      5.0
2  Blade Runner        5.0      NaN
3    Braveheart        4.0      NaN